/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    date?: string;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderItem"][];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubtaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubtaskResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubtaskResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subtasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubtaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubtaskResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderItem"][];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/note-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    projectId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteGroupResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNoteGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteGroupResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteGroupResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/note-groups/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderItem"][];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/note-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNoteGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteGroupResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    groupId?: string;
                    projectId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NoteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/notes/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderItem"][];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/focus-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddFocusSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily-plans/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDailyPlan"];
        put: operations["UpsertDailyPlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSettings"];
        put: operations["SaveSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetReportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurrence/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRecurrenceRule"];
        put?: never;
        post?: never;
        delete: operations["DeleteRecurrenceSeries"];
        options?: never;
        head?: never;
        patch: operations["UpdateRecurrenceRule"];
        trace?: never;
    };
    "/api/v1/recurrence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateRecurringTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurrence/rules/{ruleId}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateRecurrenceSeries"];
        trace?: never;
    };
    "/api/v1/recurrence/rules/{ruleId}/delete-future": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteRecurrenceSeriesFuture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurrence/instances/{taskId}/detach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DetachRecurrenceInstance"];
        trace?: never;
    };
    "/api/v1/recurrence/ensure-instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EnsureRecurrenceInstances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Sync"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Public OpenAPI-visible response for register / login / refresh. */
        AuthTokenResponse: {
            /** @description The access token. */
            accessToken: string;
            /** @description Refresh token — absent on web (httpOnly cookie); present for native clients. */
            refreshToken: string;
            /**
             * Format: int32
             * @description Seconds until the access token expires.
             */
            expiresIn: number | string;
            /** @description The authenticated user's public profile. */
            user: components["schemas"]["AuthTokenUser"];
        };
        AuthTokenUser: {
            /** Format: uuid */
            id: string;
            email: string;
            timeZoneId: string;
        };
        CompletedTaskReportItem: {
            /** Format: uuid */
            id: string;
            project: string;
            /** Format: date */
            date: string;
        };
        CreateFocusSessionRequest: {
            /** Format: uuid */
            taskId: null | string;
            project: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** Format: int32 */
            minutes: number | string;
            /** Format: date */
            date: string;
            /** Format: uuid */
            id?: null | string;
        };
        CreateNoteGroupRequest: {
            name: string;
            emoji: null | string;
            /** Format: uuid */
            projectId: null | string;
            rank?: null | string;
            /** Format: uuid */
            id?: null | string;
        };
        CreateNoteRequest: {
            /** Format: uuid */
            groupId: null | string;
            /** Format: uuid */
            projectId: null | string;
            title: string;
            content: null | string;
            rank?: null | string;
            /** Format: uuid */
            id?: null | string;
        };
        CreateProjectRequest: {
            name: string;
            color: string;
            emoji: string;
            rank?: null | string;
            /** Format: uuid */
            id?: null | string;
        };
        CreateRecurringTaskRequest: {
            task: components["schemas"]["RecurringTaskInput"];
            rule: components["schemas"]["RecurrenceRuleInput"];
        };
        CreateSubtaskRequest: {
            /** Format: uuid */
            id: null | string;
            title: string;
        };
        CreateTaskRequest: {
            /** Format: uuid */
            id: null | string;
            title: string;
            notes: null | string;
            /** Format: uuid */
            projectId: null | string;
            labels: null | string[];
            source: null | string;
            status: null | components["schemas"]["TaskStatus"];
            /** Format: date */
            plannedDate: null | string;
            /** Format: date-time */
            scheduledStart: null | string;
            /** Format: date-time */
            scheduledEnd: null | string;
            /** Format: int32 */
            durationMinutes: null | number | string;
            /** Format: int32 */
            priority: null | number | string;
            /** Format: int32 */
            reminderMinutes: null | number | string;
            rank: null | string;
            /** Format: date */
            dueDate: null | string;
        };
        DailyPlanReportItem: {
            /** Format: date */
            date: string;
            /** Format: date-time */
            committedAt: string;
            plannedTaskIds: string[];
            /** Format: int32 */
            plannedMinutes: number | string;
        };
        DailyPlanResponse: {
            /** Format: date */
            date: string;
            /** Format: date-time */
            committedAt: string;
            plannedTaskIds: string[];
            /** Format: int32 */
            plannedMinutes: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DailyPlanSyncRow: {
            /** Format: date */
            date: string;
            /** Format: date-time */
            committedAt: string;
            plannedTaskIds: string[];
            /** Format: int32 */
            plannedMinutes: number | string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        DeleteSeriesFutureRequest: {
            /** Format: date */
            fromDate: string;
        };
        FocusSessionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: null | string;
            project: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** Format: int32 */
            minutes: number | string;
            /** Format: date */
            date: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FocusSessionSyncRow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: null | string;
            project: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** Format: int32 */
            minutes: number | string;
            /** Format: date */
            date: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LogoutRequest: {
            refreshToken: null | string;
        };
        NoteGroupResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            emoji: string;
            /** Format: uuid */
            projectId: null | string;
            rank: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NoteGroupSyncRow: {
            /** Format: uuid */
            id: string;
            name: string;
            emoji: string;
            /** Format: uuid */
            projectId: null | string;
            rank: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        NoteResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            groupId: null | string;
            /** Format: uuid */
            projectId: null | string;
            title: string;
            content: string;
            rank: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NoteSyncRow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            groupId: null | string;
            /** Format: uuid */
            projectId: null | string;
            title: string;
            content: string;
            rank: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
            emoji: string;
            rank: string;
            /** Format: int32 */
            actualTimeMinutes: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectSyncRow: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
            emoji: string;
            rank: string;
            /** Format: int32 */
            actualTimeMinutes: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        /** @enum {unknown} */
        RecurrenceEndType: "Never" | "Count" | "Date";
        /** @enum {unknown} */
        RecurrenceFrequency: "Daily" | "Weekly";
        RecurrenceRuleInput: {
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Format: int32 */
            interval: number | string;
            daysOfWeek: (number | string)[];
            endType: components["schemas"]["RecurrenceEndType"];
            /** Format: int32 */
            endCount: null | number | string;
            /** Format: date */
            endDate: null | string;
            /** Format: uuid */
            id?: null | string;
        };
        RecurrenceRuleResponse: {
            /** Format: uuid */
            id: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Format: int32 */
            interval: number | string;
            daysOfWeek: (number | string)[];
            endType: components["schemas"]["RecurrenceEndType"];
            /** Format: int32 */
            endCount: null | number | string;
            /** Format: date */
            endDate: null | string;
            /** Format: date */
            generatedUntil: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RecurrenceRuleSyncRow: {
            /** Format: uuid */
            id: string;
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Format: int32 */
            interval: number | string;
            daysOfWeek: (number | string)[];
            endType: components["schemas"]["RecurrenceEndType"];
            /** Format: int32 */
            endCount: null | number | string;
            /** Format: date */
            endDate: null | string;
            /** Format: date */
            generatedUntil: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        RecurringTaskInput: {
            title: string;
            notes: string;
            /** Format: uuid */
            projectId: null | string;
            labels: string[];
            source: string;
            /** Format: date */
            plannedDate: null | string;
            /** Format: int32 */
            durationMinutes: number | string;
            /** Format: int32 */
            priority: null | number | string;
            /** Format: int32 */
            reminderMinutes: null | number | string;
            /** Format: uuid */
            id?: null | string;
        };
        RefreshRequest: {
            refreshToken: null | string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        ReorderItem: {
            /** Format: uuid */
            id: string;
            rank: string;
        };
        ReportDataResponse: {
            completedTasks: components["schemas"]["CompletedTaskReportItem"][];
            sessions: components["schemas"]["SessionReportItem"][];
            dailyPlans: components["schemas"]["DailyPlanReportItem"][];
        };
        SaveSettingsRequest: {
            settings: {
                [key: string]: string;
            };
            timeZoneId?: null | string;
        };
        SessionReportItem: {
            project: string;
            /** Format: int32 */
            minutes: number | string;
            /** Format: date */
            date: string;
        };
        SettingsResponse: {
            settings: {
                [key: string]: string;
            };
            timeZoneId: string;
        };
        SettingSyncRow: {
            key: string;
            value: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        SubtaskResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            title: string;
            completed: boolean;
            /** Format: int32 */
            sortOrder: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SubtaskSyncRow: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            title: string;
            completed: boolean;
            /** Format: int32 */
            sortOrder: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        SyncChanges: {
            tasks: components["schemas"]["TaskSyncRow"][];
            subtasks: components["schemas"]["SubtaskSyncRow"][];
            projects: components["schemas"]["ProjectSyncRow"][];
            noteGroups: components["schemas"]["NoteGroupSyncRow"][];
            notes: components["schemas"]["NoteSyncRow"][];
            recurrenceRules: components["schemas"]["RecurrenceRuleSyncRow"][];
            focusSessions: components["schemas"]["FocusSessionSyncRow"][];
            dailyPlans: components["schemas"]["DailyPlanSyncRow"][];
            settings: components["schemas"]["SettingSyncRow"][];
        };
        SyncResponse: {
            changes: components["schemas"]["SyncChanges"];
            /** Format: int64 */
            nextSince: number | string;
            hasMore: boolean;
            /** @default false */
            fullResyncRequired: boolean;
        };
        TaskResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            notes: string;
            /** Format: uuid */
            projectId: null | string;
            labels: string[];
            source: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: date */
            plannedDate: null | string;
            /** Format: date-time */
            scheduledStart: null | string;
            /** Format: date-time */
            scheduledEnd: null | string;
            /** Format: int32 */
            durationMinutes: number | string;
            /** Format: int32 */
            actualTimeMinutes: number | string;
            /** Format: int32 */
            priority: null | number | string;
            /** Format: int32 */
            reminderMinutes: null | number | string;
            rank: string;
            /** Format: date */
            dueDate: null | string;
            /** Format: uuid */
            recurrenceRuleId: null | string;
            isRecurrenceTemplate: boolean;
            recurrenceDetached: boolean;
            /** Format: date */
            recurrenceOriginalDate: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            subtasks: components["schemas"]["SubtaskResponse"][];
        };
        /** @enum {unknown} */
        TaskStatus: "Inbox" | "Backlog" | "Planned" | "Scheduled" | "Done" | "Archived";
        TaskSyncRow: {
            /** Format: uuid */
            id: string;
            title: string;
            notes: string;
            /** Format: uuid */
            projectId: null | string;
            labels: string[];
            source: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: date */
            plannedDate: null | string;
            /** Format: date-time */
            scheduledStart: null | string;
            /** Format: date-time */
            scheduledEnd: null | string;
            /** Format: int32 */
            durationMinutes: number | string;
            /** Format: int32 */
            actualTimeMinutes: number | string;
            /** Format: int32 */
            priority: null | number | string;
            /** Format: int32 */
            reminderMinutes: null | number | string;
            rank: string;
            /** Format: date */
            dueDate: null | string;
            /** Format: uuid */
            recurrenceRuleId: null | string;
            isRecurrenceTemplate: boolean;
            recurrenceDetached: boolean;
            /** Format: date */
            recurrenceOriginalDate: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            changeSeq: number | string;
            /** Format: date-time */
            deletedAt: null | string;
        };
        UpdateNoteGroupRequest: {
            name: null | string;
            emoji: null | string;
            /** Format: uuid */
            projectId: null | string;
            rank: null | string;
        };
        UpdateNoteRequest: {
            /** Format: uuid */
            groupId: null | string;
            /** Format: uuid */
            projectId: null | string;
            title: null | string;
            content: null | string;
            rank: null | string;
        };
        UpdateProjectRequest: {
            name?: null | string;
            color?: null | string;
            emoji?: null | string;
            rank?: null | string;
            /** Format: int32 */
            actualTimeMinutes?: null | number | string;
        };
        UpdateRuleRequest: {
            frequency: components["schemas"]["RecurrenceFrequency"];
            /** Format: int32 */
            interval: number | string;
            daysOfWeek: (number | string)[];
            endType: components["schemas"]["RecurrenceEndType"];
            /** Format: int32 */
            endCount: null | number | string;
            /** Format: date */
            endDate: null | string;
        };
        UpdateSeriesRequest: {
            title: null | string;
            notes: null | string;
            /** Format: uuid */
            projectId: null | string;
            labels: null | string[];
            /** Format: int32 */
            durationMinutes: null | number | string;
            /** Format: int32 */
            priority: null | number | string;
            /** Format: int32 */
            reminderMinutes: null | number | string;
        };
        UpdateSubtaskRequest: {
            title: null | string;
            completed: null | boolean;
            /** Format: int32 */
            sortOrder: null | number | string;
        };
        UpdateTaskRequest: {
            title: null | string;
            notes: null | string;
            /** Format: uuid */
            projectId: null | string;
            labels: null | string[];
            source: null | string;
            status: null | components["schemas"]["TaskStatus"];
            /** Format: date */
            plannedDate: null | string;
            /** Format: date-time */
            scheduledStart: null | string;
            /** Format: date-time */
            scheduledEnd: null | string;
            /** Format: int32 */
            durationMinutes: null | number | string;
            /** Format: int32 */
            actualTimeMinutes: null | number | string;
            /** Format: int32 */
            priority: null | number | string;
            /** Format: int32 */
            reminderMinutes: null | number | string;
            rank: null | string;
            /** Format: date */
            dueDate: null | string;
            /** Format: date-time */
            completedAt: null | string;
        };
        UpsertDailyPlanRequest: {
            plannedTaskIds: string[];
            /** Format: int32 */
            plannedMinutes: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AddFocusSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFocusSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FocusSessionResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FocusSessionResponse"];
                };
            };
        };
    };
    GetDailyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPlanResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpsertDailyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDailyPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPlanResponse"];
                };
            };
        };
    };
    GetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    SaveSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    GetReportData: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDataResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetRecurrenceRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurrenceRuleResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteRecurrenceSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateRecurrenceRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurrenceRuleResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateRecurringTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringTaskRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    UpdateRecurrenceSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSeriesRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteRecurrenceSeriesFuture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteSeriesFutureRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DetachRecurrenceInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EnsureRecurrenceInstances: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    Sync: {
        parameters: {
            query?: {
                since?: number | string;
                cursor?: number | string;
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
}
